client: control: InGameController: fix incompatible types regression
Broken-By: 56472fe06b56f46de5964445bfd1d9b4fa752843

compile:
    [javac] Compiling 286 source files to /home/nekrad/src/packaging/pkg/freecol.git/build
    [javac] /home/nekrad/src/packaging/pkg/freecol.git/src/net/sf/freecol/client/control/InGameController.java:159: error: incompatible types
    [javac]         = Collections.synchronizedMap(new HashMap<>());
    [javac]                                      ^
    [javac]   required: Map<String,Integer>
    [javac]   found:    Map<Object,Object>