(S) common: networking: ChangeSet: fix missing type conversion regression
Broken-By: f47e5985fed3bb2fb4cad9d4b13318049a634354
Submitted: 2017-01-25

compile:
    [javac] Compiling 459 source files to /home/nekrad/src/packaging/pkg/freecol.git/build
    [javac] /home/nekrad/src/packaging/pkg/freecol.git/src/net/sf/freecol/common/networking/ChangeSet.java:807: error: no suitable constructor found for UpdateMessage(ServerPlayer,List<FreeColGameObject>)
    [javac]                 : new UpdateMessage(serverPlayer,
    [javac]                   ^
    [javac]     constructor UpdateMessage.UpdateMessage(Game,Element) is not applicable
    [javac]       (actual argument ServerPlayer cannot be converted to Game by method invocation conversion)
    [javac]     constructor UpdateMessage.UpdateMessage(ServerPlayer,List<FreeColObject>) is not applicable
    [javac]       (actual argument List<FreeColGameObject> cannot be converted to List<FreeColObject> by method invocation conversion)
    [javac] 1 error