common: model: Specification: fix type mismatch regression
    [javac] /home/nekrad/src/packaging/pkg/freecol.git/src/net/sf/freecol/common/model/Specification.java:1782: error: no suitable met
hod found for add(Option)
    [javac]                 result.add(o);
    [javac]                       ^
    [javac]     method Collection.add(OptionGroup) is not applicable
    [javac]       (argument mismatch; Option cannot be converted to OptionGroup)
    [javac]     method List.add(OptionGroup) is not applicable
    [javac]       (argument mismatch; Option cannot be converted to OptionGroup)

Broken-by: d42604670fe2599836032f0f9190d2cf68b290f8