(S) common: model: Specification: fix type mismatch
Submitted: 2017-02-13

compile:
    [javac] Compiling 374 source files to /home/nekrad/src/packaging/pkg/freecol.git/build
    [javac] /home/nekrad/src/packaging/pkg/freecol.git/src/net/sf/freecol/common/model/Specification.java:2013: error: incompatible types
    [javac]         Collection<AbstractOption> allG = new HashSet<>(allOptionGroups.values());
    [javac]                                           ^
    [javac]   required: Collection<AbstractOption>
    [javac]   found:    HashSet<OptionGroup>